version: "3.9"
services:
  backend:
    build: ./backend
    container_name: pf-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - SQLITE_STORAGE=./data/database.sqlite
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: pf-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
